ALTER TYPE product_category ADD VALUE IF NOT EXISTS 'FOOD';
ALTER TYPE product_category ADD VALUE IF NOT EXISTS 'GRAPPA';
ALTER TYPE product_category ADD VALUE IF NOT EXISTS 'OTHER_LIQUOR';
ALTER TYPE product_category ADD VALUE IF NOT EXISTS 'OTHER';
